# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 1001, 641))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 351, 141))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setLineWidth(1)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setIndent(-1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_9.addWidget(self.label_4)
        self.pushButton_18 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.verticalLayout_9.addWidget(self.pushButton_18)
        self.pushButton_19 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.verticalLayout_9.addWidget(self.pushButton_19)
        self.pushButton_26 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.verticalLayout_9.addWidget(self.pushButton_26)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_10.addWidget(self.label_5)
        self.pushButton_20 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.verticalLayout_10.addWidget(self.pushButton_20)
        self.pushButton_21 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.verticalLayout_10.addWidget(self.pushButton_21)
        self.pushButton_27 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.verticalLayout_10.addWidget(self.pushButton_27)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_11.addWidget(self.label_6)
        self.pushButton_22 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.verticalLayout_11.addWidget(self.pushButton_22)
        self.pushButton_23 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.verticalLayout_11.addWidget(self.pushButton_23)
        self.pushButton_28 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.verticalLayout_11.addWidget(self.pushButton_28)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_12.addWidget(self.label_7)
        self.pushButton_24 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.verticalLayout_12.addWidget(self.pushButton_24)
        self.pushButton_25 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.verticalLayout_12.addWidget(self.pushButton_25)
        self.pushButton_29 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.verticalLayout_12.addWidget(self.pushButton_29)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.pushButton_15 = QtGui.QPushButton(self.groupBox)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 176, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 240, 301, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 261, 121))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_4 = QtGui.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.pushButton_10 = QtGui.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout_5.addWidget(self.pushButton_10)
        self.pushButton_11 = QtGui.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.verticalLayout_5.addWidget(self.pushButton_11)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_14.setGeometry(QtCore.QRect(19, 156, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 450, 581, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(9, 29, 563, 101))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEdit_79 = QtGui.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_79.setFont(font)
        self.lineEdit_79.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_79.setObjectName(_fromUtf8("lineEdit_79"))
        self.horizontalLayout_4.addWidget(self.lineEdit_79)
        self.lineEdit_4 = QtGui.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.lineEdit_8 = QtGui.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_5.addWidget(self.lineEdit_8)
        self.lineEdit_7 = QtGui.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_5.addWidget(self.lineEdit_7)
        self.lineEdit_9 = QtGui.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_5.addWidget(self.lineEdit_9)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(320, 240, 431, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pushButton_34 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_34.setGeometry(QtCore.QRect(10, 90, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_4)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(11, 40, 404, 41))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEdit_11 = QtGui.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_6.addWidget(self.lineEdit_11)
        self.lineEdit_10 = QtGui.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_6.addWidget(self.lineEdit_10)
        self.lineEdit_12 = QtGui.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_6.addWidget(self.lineEdit_12)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(410, 10, 391, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayoutWidget_7 = QtGui.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(20, 30, 351, 181))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_13.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet(_fromUtf8(""))
        self.label_13.setLineWidth(1)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(False)
        self.label_13.setIndent(-1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_13.addWidget(self.label_13)
        self.lineEdit_13 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.verticalLayout_13.addWidget(self.lineEdit_13)
        self.pushButton_32 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.verticalLayout_13.addWidget(self.pushButton_32)
        self.pushButton_35 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet(_fromUtf8("background-color: rgb(255, 221, 230);"))
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.verticalLayout_13.addWidget(self.pushButton_35)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_14.addWidget(self.label_14)
        self.lineEdit_14 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.verticalLayout_14.addWidget(self.lineEdit_14)
        self.pushButton_36 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName(_fromUtf8("pushButton_36"))
        self.verticalLayout_14.addWidget(self.pushButton_36)
        self.pushButton_38 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet(_fromUtf8("background-color: rgb(255, 221, 230);"))
        self.pushButton_38.setObjectName(_fromUtf8("pushButton_38"))
        self.verticalLayout_14.addWidget(self.pushButton_38)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_15.addWidget(self.label_15)
        self.lineEdit_15 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.verticalLayout_15.addWidget(self.lineEdit_15)
        self.pushButton_39 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setObjectName(_fromUtf8("pushButton_39"))
        self.verticalLayout_15.addWidget(self.pushButton_39)
        self.pushButton_41 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setStyleSheet(_fromUtf8("background-color: rgb(255, 221, 230);"))
        self.pushButton_41.setObjectName(_fromUtf8("pushButton_41"))
        self.verticalLayout_15.addWidget(self.pushButton_41)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_16.addWidget(self.label_16)
        self.lineEdit_16 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.verticalLayout_16.addWidget(self.lineEdit_16)
        self.pushButton_42 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setObjectName(_fromUtf8("pushButton_42"))
        self.verticalLayout_16.addWidget(self.pushButton_42)
        self.pushButton_46 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setStyleSheet(_fromUtf8("background-color: rgb(255, 221, 230);"))
        self.pushButton_46.setObjectName(_fromUtf8("pushButton_46"))
        self.verticalLayout_16.addWidget(self.pushButton_46)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(809, 9, 181, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.groupBox_7)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 29, 161, 131))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_21 = QtGui.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtGui.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtGui.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtGui.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_21 = QtGui.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_21)
        self.lineEdit_22 = QtGui.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_22)
        self.lineEdit_23 = QtGui.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_23)
        self.pushButton_44 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_44.setGeometry(QtCore.QRect(10, 170, 161, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setObjectName(_fromUtf8("pushButton_44"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(600, 390, 391, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.groupBox_8)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 29, 371, 131))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_25 = QtGui.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtGui.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtGui.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtGui.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_28)
        self.lineEdit_24 = QtGui.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setText(_fromUtf8(""))
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_24)
        self.lineEdit_25 = QtGui.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setText(_fromUtf8(""))
        self.lineEdit_25.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_25)
        self.lineEdit_26 = QtGui.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setText(_fromUtf8(""))
        self.lineEdit_26.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_26)
        self.lineEdit_36 = QtGui.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setText(_fromUtf8(""))
        self.lineEdit_36.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_36)
        self.pushButton_45 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_45.setGeometry(QtCore.QRect(10, 170, 371, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setObjectName(_fromUtf8("pushButton_45"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayoutWidget_10 = QtGui.QWidget(self.tab)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(10, 10, 611, 111))
        self.formLayoutWidget_10.setObjectName(_fromUtf8("formLayoutWidget_10"))
        self.formLayout_18 = QtGui.QFormLayout(self.formLayoutWidget_10)
        self.formLayout_18.setObjectName(_fromUtf8("formLayout_18"))
        self.label_51 = QtGui.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.formLayout_18.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_51)
        self.label_56 = QtGui.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.formLayout_18.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_56)
        self.label_57 = QtGui.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.formLayout_18.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_57)
        self.lineEdit_76 = QtGui.QLineEdit(self.formLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_76.sizePolicy().hasHeightForWidth())
        self.lineEdit_76.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_76.setFont(font)
        self.lineEdit_76.setText(_fromUtf8(""))
        self.lineEdit_76.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_76.setObjectName(_fromUtf8("lineEdit_76"))
        self.formLayout_18.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_76)
        self.lineEdit_77 = QtGui.QLineEdit(self.formLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_77.sizePolicy().hasHeightForWidth())
        self.lineEdit_77.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_77.setFont(font)
        self.lineEdit_77.setText(_fromUtf8(""))
        self.lineEdit_77.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_77.setObjectName(_fromUtf8("lineEdit_77"))
        self.formLayout_18.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_77)
        self.lineEdit_78 = QtGui.QLineEdit(self.formLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_78.sizePolicy().hasHeightForWidth())
        self.lineEdit_78.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_78.setFont(font)
        self.lineEdit_78.setText(_fromUtf8(""))
        self.lineEdit_78.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_78.setObjectName(_fromUtf8("lineEdit_78"))
        self.formLayout_18.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_78)
        self.horizontalLayoutWidget_11 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(10, 130, 611, 41))
        self.horizontalLayoutWidget_11.setObjectName(_fromUtf8("horizontalLayoutWidget_11"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.pushButton_31 = QtGui.QPushButton(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.horizontalLayout_26.addWidget(self.pushButton_31)
        self.pushButton_30 = QtGui.QPushButton(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.horizontalLayout_26.addWidget(self.pushButton_30)
        self.pushButton_51 = QtGui.QPushButton(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setObjectName(_fromUtf8("pushButton_51"))
        self.horizontalLayout_26.addWidget(self.pushButton_51)
        self.pushButton_54 = QtGui.QPushButton(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setObjectName(_fromUtf8("pushButton_54"))
        self.horizontalLayout_26.addWidget(self.pushButton_54)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 971, 241))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 30, 953, 201))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_17.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setStyleSheet(_fromUtf8(""))
        self.label_17.setLineWidth(1)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setScaledContents(False)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setWordWrap(False)
        self.label_17.setIndent(-1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_17.addWidget(self.label_17)
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_29 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_29)
        self.label_34 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_35)
        self.lineEdit_17 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_17.sizePolicy().hasHeightForWidth())
        self.lineEdit_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_17)
        self.lineEdit_18 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_18.sizePolicy().hasHeightForWidth())
        self.lineEdit_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_18)
        self.lineEdit_19 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_19.sizePolicy().hasHeightForWidth())
        self.lineEdit_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_19)
        self.verticalLayout_17.addLayout(self.formLayout_7)
        self.pushButton_33 = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.verticalLayout_17.addWidget(self.pushButton_33)
        self.pushButton_47 = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setObjectName(_fromUtf8("pushButton_47"))
        self.verticalLayout_17.addWidget(self.pushButton_47)
        self.horizontalLayout_8.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setAutoFillBackground(False)
        self.label_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_18.addWidget(self.label_18)
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.lineEdit_48 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_48.sizePolicy().hasHeightForWidth())
        self.lineEdit_48.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_48.setFont(font)
        self.lineEdit_48.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_48.setObjectName(_fromUtf8("lineEdit_48"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_48)
        self.lineEdit_58 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_58.sizePolicy().hasHeightForWidth())
        self.lineEdit_58.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_58.setFont(font)
        self.lineEdit_58.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_58.setObjectName(_fromUtf8("lineEdit_58"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_58)
        self.lineEdit_59 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_59.sizePolicy().hasHeightForWidth())
        self.lineEdit_59.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_59.setFont(font)
        self.lineEdit_59.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_59.setObjectName(_fromUtf8("lineEdit_59"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_59)
        self.verticalLayout_18.addLayout(self.formLayout_8)
        self.pushButton_37 = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setObjectName(_fromUtf8("pushButton_37"))
        self.verticalLayout_18.addWidget(self.pushButton_37)
        self.pushButton_48 = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setObjectName(_fromUtf8("pushButton_48"))
        self.verticalLayout_18.addWidget(self.pushButton_48)
        self.horizontalLayout_8.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_19.addWidget(self.label_19)
        self.formLayout_15 = QtGui.QFormLayout()
        self.formLayout_15.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_15.setObjectName(_fromUtf8("formLayout_15"))
        self.lineEdit_66 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_66.sizePolicy().hasHeightForWidth())
        self.lineEdit_66.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_66.setFont(font)
        self.lineEdit_66.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_66.setObjectName(_fromUtf8("lineEdit_66"))
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_66)
        self.lineEdit_67 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_67.sizePolicy().hasHeightForWidth())
        self.lineEdit_67.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_67.setFont(font)
        self.lineEdit_67.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_67.setObjectName(_fromUtf8("lineEdit_67"))
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_67)
        self.lineEdit_68 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_68.sizePolicy().hasHeightForWidth())
        self.lineEdit_68.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_68.setFont(font)
        self.lineEdit_68.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_68.setObjectName(_fromUtf8("lineEdit_68"))
        self.formLayout_15.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_68)
        self.verticalLayout_19.addLayout(self.formLayout_15)
        self.pushButton_40 = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setObjectName(_fromUtf8("pushButton_40"))
        self.verticalLayout_19.addWidget(self.pushButton_40)
        self.pushButton_49 = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setObjectName(_fromUtf8("pushButton_49"))
        self.verticalLayout_19.addWidget(self.pushButton_49)
        self.horizontalLayout_8.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_20.addWidget(self.label_20)
        self.formLayout_16 = QtGui.QFormLayout()
        self.formLayout_16.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_16.setObjectName(_fromUtf8("formLayout_16"))
        self.lineEdit_69 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_69.sizePolicy().hasHeightForWidth())
        self.lineEdit_69.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_69.setFont(font)
        self.lineEdit_69.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_69.setObjectName(_fromUtf8("lineEdit_69"))
        self.formLayout_16.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_69)
        self.lineEdit_70 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_70.sizePolicy().hasHeightForWidth())
        self.lineEdit_70.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_70.setFont(font)
        self.lineEdit_70.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_70.setObjectName(_fromUtf8("lineEdit_70"))
        self.formLayout_16.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_70)
        self.lineEdit_71 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_71.sizePolicy().hasHeightForWidth())
        self.lineEdit_71.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_71.setFont(font)
        self.lineEdit_71.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_71.setObjectName(_fromUtf8("lineEdit_71"))
        self.formLayout_16.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_71)
        self.verticalLayout_20.addLayout(self.formLayout_16)
        self.pushButton_43 = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setObjectName(_fromUtf8("pushButton_43"))
        self.verticalLayout_20.addWidget(self.pushButton_43)
        self.pushButton_50 = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setObjectName(_fromUtf8("pushButton_50"))
        self.verticalLayout_20.addWidget(self.pushButton_50)
        self.horizontalLayout_8.addLayout(self.verticalLayout_20)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 260, 481, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setFlat(False)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayoutWidget_9 = QtGui.QWidget(self.groupBox_9)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(7, 25, 461, 131))
        self.horizontalLayoutWidget_9.setObjectName(_fromUtf8("horizontalLayoutWidget_9"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.formLayout_17 = QtGui.QFormLayout()
        self.formLayout_17.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_17.setObjectName(_fromUtf8("formLayout_17"))
        self.label_52 = QtGui.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.formLayout_17.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_52)
        self.lineEdit_72 = QtGui.QLineEdit(self.horizontalLayoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_72.sizePolicy().hasHeightForWidth())
        self.lineEdit_72.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_72.setFont(font)
        self.lineEdit_72.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_72.setObjectName(_fromUtf8("lineEdit_72"))
        self.formLayout_17.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_72)
        self.label_53 = QtGui.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.formLayout_17.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_53)
        self.lineEdit_73 = QtGui.QLineEdit(self.horizontalLayoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_73.sizePolicy().hasHeightForWidth())
        self.lineEdit_73.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_73.setFont(font)
        self.lineEdit_73.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_73.setObjectName(_fromUtf8("lineEdit_73"))
        self.formLayout_17.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_73)
        self.verticalLayout_21.addLayout(self.formLayout_17)
        self.pushButton_52 = QtGui.QPushButton(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setObjectName(_fromUtf8("pushButton_52"))
        self.verticalLayout_21.addWidget(self.pushButton_52)
        self.horizontalLayout_17.addLayout(self.verticalLayout_21)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_10.setGeometry(QtCore.QRect(500, 260, 481, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayoutWidget_10 = QtGui.QWidget(self.groupBox_10)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(7, 25, 461, 131))
        self.horizontalLayoutWidget_10.setObjectName(_fromUtf8("horizontalLayoutWidget_10"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.formLayout_19 = QtGui.QFormLayout()
        self.formLayout_19.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_19.setObjectName(_fromUtf8("formLayout_19"))
        self.label_54 = QtGui.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.formLayout_19.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_54)
        self.lineEdit_74 = QtGui.QLineEdit(self.horizontalLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_74.sizePolicy().hasHeightForWidth())
        self.lineEdit_74.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_74.setFont(font)
        self.lineEdit_74.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_74.setObjectName(_fromUtf8("lineEdit_74"))
        self.formLayout_19.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_74)
        self.label_55 = QtGui.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.formLayout_19.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_55)
        self.lineEdit_75 = QtGui.QLineEdit(self.horizontalLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_75.sizePolicy().hasHeightForWidth())
        self.lineEdit_75.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_75.setFont(font)
        self.lineEdit_75.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_75.setObjectName(_fromUtf8("lineEdit_75"))
        self.formLayout_19.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_75)
        self.verticalLayout_22.addLayout(self.formLayout_19)
        self.pushButton_53 = QtGui.QPushButton(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setObjectName(_fromUtf8("pushButton_53"))
        self.verticalLayout_22.addWidget(self.pushButton_53)
        self.horizontalLayout_25.addLayout(self.verticalLayout_22)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 1001, 61))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSpacing(18)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.pushButton_12 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.pushButton_13 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 127);\n"
"color: rgb(170, 0, );"))
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.horizontalLayout_2.addWidget(self.pushButton_1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.pushButton_12)
        MainWindow.setTabOrder(self.pushButton_12, self.pushButton_13)
        MainWindow.setTabOrder(self.pushButton_13, self.pushButton_1)
        MainWindow.setTabOrder(self.pushButton_1, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton_18)
        MainWindow.setTabOrder(self.pushButton_18, self.pushButton_19)
        MainWindow.setTabOrder(self.pushButton_19, self.pushButton_26)
        MainWindow.setTabOrder(self.pushButton_26, self.pushButton_20)
        MainWindow.setTabOrder(self.pushButton_20, self.pushButton_21)
        MainWindow.setTabOrder(self.pushButton_21, self.pushButton_27)
        MainWindow.setTabOrder(self.pushButton_27, self.pushButton_22)
        MainWindow.setTabOrder(self.pushButton_22, self.pushButton_23)
        MainWindow.setTabOrder(self.pushButton_23, self.pushButton_28)
        MainWindow.setTabOrder(self.pushButton_28, self.pushButton_24)
        MainWindow.setTabOrder(self.pushButton_24, self.pushButton_25)
        MainWindow.setTabOrder(self.pushButton_25, self.pushButton_29)
        MainWindow.setTabOrder(self.pushButton_29, self.pushButton_15)
        MainWindow.setTabOrder(self.pushButton_15, self.lineEdit_13)
        MainWindow.setTabOrder(self.lineEdit_13, self.pushButton_32)
        MainWindow.setTabOrder(self.pushButton_32, self.pushButton_35)
        MainWindow.setTabOrder(self.pushButton_35, self.lineEdit_14)
        MainWindow.setTabOrder(self.lineEdit_14, self.pushButton_36)
        MainWindow.setTabOrder(self.pushButton_36, self.pushButton_38)
        MainWindow.setTabOrder(self.pushButton_38, self.lineEdit_15)
        MainWindow.setTabOrder(self.lineEdit_15, self.pushButton_39)
        MainWindow.setTabOrder(self.pushButton_39, self.pushButton_41)
        MainWindow.setTabOrder(self.pushButton_41, self.lineEdit_16)
        MainWindow.setTabOrder(self.lineEdit_16, self.pushButton_42)
        MainWindow.setTabOrder(self.pushButton_42, self.pushButton_46)
        MainWindow.setTabOrder(self.pushButton_46, self.lineEdit_23)
        MainWindow.setTabOrder(self.lineEdit_23, self.lineEdit_22)
        MainWindow.setTabOrder(self.lineEdit_22, self.lineEdit_21)
        MainWindow.setTabOrder(self.lineEdit_21, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.pushButton_44)
        MainWindow.setTabOrder(self.pushButton_44, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_10)
        MainWindow.setTabOrder(self.pushButton_10, self.pushButton_11)
        MainWindow.setTabOrder(self.pushButton_11, self.pushButton_14)
        MainWindow.setTabOrder(self.pushButton_14, self.lineEdit_11)
        MainWindow.setTabOrder(self.lineEdit_11, self.lineEdit_10)
        MainWindow.setTabOrder(self.lineEdit_10, self.lineEdit_12)
        MainWindow.setTabOrder(self.lineEdit_12, self.pushButton_34)
        MainWindow.setTabOrder(self.pushButton_34, self.lineEdit_24)
        MainWindow.setTabOrder(self.lineEdit_24, self.lineEdit_25)
        MainWindow.setTabOrder(self.lineEdit_25, self.lineEdit_26)
        MainWindow.setTabOrder(self.lineEdit_26, self.lineEdit_36)
        MainWindow.setTabOrder(self.lineEdit_36, self.pushButton_45)
        MainWindow.setTabOrder(self.pushButton_45, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_79)
        MainWindow.setTabOrder(self.lineEdit_79, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.lineEdit_76)
        MainWindow.setTabOrder(self.lineEdit_76, self.lineEdit_77)
        MainWindow.setTabOrder(self.lineEdit_77, self.lineEdit_78)
        MainWindow.setTabOrder(self.lineEdit_78, self.pushButton_31)
        MainWindow.setTabOrder(self.pushButton_31, self.pushButton_30)
        MainWindow.setTabOrder(self.pushButton_30, self.pushButton_51)
        MainWindow.setTabOrder(self.pushButton_51, self.pushButton_54)
        MainWindow.setTabOrder(self.pushButton_54, self.lineEdit_17)
        MainWindow.setTabOrder(self.lineEdit_17, self.lineEdit_18)
        MainWindow.setTabOrder(self.lineEdit_18, self.lineEdit_19)
        MainWindow.setTabOrder(self.lineEdit_19, self.pushButton_33)
        MainWindow.setTabOrder(self.pushButton_33, self.pushButton_47)
        MainWindow.setTabOrder(self.pushButton_47, self.lineEdit_48)
        MainWindow.setTabOrder(self.lineEdit_48, self.lineEdit_58)
        MainWindow.setTabOrder(self.lineEdit_58, self.lineEdit_59)
        MainWindow.setTabOrder(self.lineEdit_59, self.pushButton_37)
        MainWindow.setTabOrder(self.pushButton_37, self.pushButton_48)
        MainWindow.setTabOrder(self.pushButton_48, self.lineEdit_66)
        MainWindow.setTabOrder(self.lineEdit_66, self.lineEdit_67)
        MainWindow.setTabOrder(self.lineEdit_67, self.lineEdit_68)
        MainWindow.setTabOrder(self.lineEdit_68, self.pushButton_40)
        MainWindow.setTabOrder(self.pushButton_40, self.pushButton_49)
        MainWindow.setTabOrder(self.pushButton_49, self.lineEdit_69)
        MainWindow.setTabOrder(self.lineEdit_69, self.lineEdit_70)
        MainWindow.setTabOrder(self.lineEdit_70, self.lineEdit_71)
        MainWindow.setTabOrder(self.lineEdit_71, self.pushButton_43)
        MainWindow.setTabOrder(self.pushButton_43, self.pushButton_50)
        MainWindow.setTabOrder(self.pushButton_50, self.lineEdit_72)
        MainWindow.setTabOrder(self.lineEdit_72, self.lineEdit_73)
        MainWindow.setTabOrder(self.lineEdit_73, self.pushButton_52)
        MainWindow.setTabOrder(self.pushButton_52, self.lineEdit_74)
        MainWindow.setTabOrder(self.lineEdit_74, self.lineEdit_75)
        MainWindow.setTabOrder(self.lineEdit_75, self.pushButton_53)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Cable Robot Control Panel v0.001 Pre-Alpha by Afdhal", None))
        self.groupBox.setTitle(_translate("MainWindow", "Relative Individual Control", None))
        self.label_4.setText(_translate("MainWindow", "Winch A", None))
        self.pushButton_18.setText(_translate("MainWindow", "+A", None))
        self.pushButton_19.setText(_translate("MainWindow", "-A", None))
        self.pushButton_26.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set the current cable length as reference 0.</p></body></html>", None))
        self.pushButton_26.setText(_translate("MainWindow", "Zero A", None))
        self.label_5.setText(_translate("MainWindow", "Winch B", None))
        self.pushButton_20.setText(_translate("MainWindow", "+B", None))
        self.pushButton_21.setText(_translate("MainWindow", "-B", None))
        self.pushButton_27.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set the current cable length as reference 0.</p></body></html>", None))
        self.pushButton_27.setText(_translate("MainWindow", "Zero B", None))
        self.label_6.setText(_translate("MainWindow", "Winch C", None))
        self.pushButton_22.setText(_translate("MainWindow", "+C", None))
        self.pushButton_23.setText(_translate("MainWindow", "-C", None))
        self.pushButton_28.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set the current cable length as reference 0.</p></body></html>", None))
        self.pushButton_28.setText(_translate("MainWindow", "Zero C", None))
        self.label_7.setText(_translate("MainWindow", "Winch D", None))
        self.pushButton_24.setText(_translate("MainWindow", "+D", None))
        self.pushButton_25.setText(_translate("MainWindow", "-D", None))
        self.pushButton_29.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set the current cable length as reference 0.</p></body></html>", None))
        self.pushButton_29.setText(_translate("MainWindow", "Zero D", None))
        self.pushButton_15.setText(_translate("MainWindow", "Home All via Length", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Relative Coordinated Control", None))
        self.label.setText(_translate("MainWindow", "X-Axis", None))
        self.pushButton_2.setText(_translate("MainWindow", "+X", None))
        self.pushButton_3.setText(_translate("MainWindow", "-X", None))
        self.label_2.setText(_translate("MainWindow", "Y-Axis", None))
        self.pushButton_4.setText(_translate("MainWindow", "+Y", None))
        self.pushButton_5.setText(_translate("MainWindow", "-Y", None))
        self.label_3.setText(_translate("MainWindow", "Z-Axis", None))
        self.pushButton_10.setText(_translate("MainWindow", "+Z", None))
        self.pushButton_11.setText(_translate("MainWindow", "-Z", None))
        self.pushButton_14.setText(_translate("MainWindow", "Home All via Coordinate", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Settings", None))
        self.label_9.setText(_translate("MainWindow", "Travel Increment (mm)", None))
        self.lineEdit_2.setText(_translate("MainWindow", "10", None))
        self.label_10.setText(_translate("MainWindow", "Homing XYZ Coordinate (mm)", None))
        self.lineEdit_79.setText(_translate("MainWindow", "0", None))
        self.lineEdit_4.setText(_translate("MainWindow", "0", None))
        self.lineEdit_5.setText(_translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "Homing ABCD Length (mm)", None))
        self.lineEdit_6.setText(_translate("MainWindow", "0", None))
        self.lineEdit_8.setText(_translate("MainWindow", "1000", None))
        self.lineEdit_7.setText(_translate("MainWindow", "1414", None))
        self.lineEdit_9.setText(_translate("MainWindow", "1000", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Absolute Coordinated Control", None))
        self.pushButton_34.setText(_translate("MainWindow", "Go to Waypoint", None))
        self.label_12.setText(_translate("MainWindow", "Waypoint XYZ (mm)", None))
        self.lineEdit_11.setText(_translate("MainWindow", "500", None))
        self.lineEdit_10.setText(_translate("MainWindow", "500", None))
        self.lineEdit_12.setText(_translate("MainWindow", "500", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Absolute Individual Control", None))
        self.label_13.setText(_translate("MainWindow", "Winch A", None))
        self.lineEdit_13.setText(_translate("MainWindow", "0", None))
        self.pushButton_32.setText(_translate("MainWindow", "Goto A", None))
        self.pushButton_35.setText(_translate("MainWindow", "Reset A", None))
        self.label_14.setText(_translate("MainWindow", "Winch B", None))
        self.lineEdit_14.setText(_translate("MainWindow", "0", None))
        self.pushButton_36.setText(_translate("MainWindow", "Goto B", None))
        self.pushButton_38.setText(_translate("MainWindow", "Reset B", None))
        self.label_15.setText(_translate("MainWindow", "Winch C", None))
        self.lineEdit_15.setText(_translate("MainWindow", "0", None))
        self.pushButton_39.setText(_translate("MainWindow", "Goto C", None))
        self.pushButton_41.setText(_translate("MainWindow", "Reset C", None))
        self.label_16.setText(_translate("MainWindow", "Winch D", None))
        self.lineEdit_16.setText(_translate("MainWindow", "0", None))
        self.pushButton_42.setText(_translate("MainWindow", "Goto D", None))
        self.pushButton_46.setText(_translate("MainWindow", "Reset D", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Target Lengths", None))
        self.label_21.setText(_translate("MainWindow", "A Length", None))
        self.label_22.setText(_translate("MainWindow", "B Length", None))
        self.label_23.setText(_translate("MainWindow", "C Length", None))
        self.label_24.setText(_translate("MainWindow", "D Length", None))
        self.lineEdit_3.setText(_translate("MainWindow", "0", None))
        self.lineEdit_21.setText(_translate("MainWindow", "0", None))
        self.lineEdit_22.setText(_translate("MainWindow", "0", None))
        self.lineEdit_23.setText(_translate("MainWindow", "0", None))
        self.pushButton_44.setText(_translate("MainWindow", "Read", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Target Coordinates", None))
        self.label_25.setText(_translate("MainWindow", "Winch A", None))
        self.label_26.setText(_translate("MainWindow", "Winch B", None))
        self.label_27.setText(_translate("MainWindow", "Winch C", None))
        self.label_28.setText(_translate("MainWindow", "Winch D", None))
        self.pushButton_45.setText(_translate("MainWindow", "Read", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Jog Control", None))
        self.label_51.setText(_translate("MainWindow", "Current Cable Length (mm)", None))
        self.label_56.setText(_translate("MainWindow", "Current PWM Duty Cycle (%)", None))
        self.label_57.setText(_translate("MainWindow", "Current RPM", None))
        self.pushButton_31.setText(_translate("MainWindow", "Read A", None))
        self.pushButton_30.setText(_translate("MainWindow", "Read B", None))
        self.pushButton_51.setText(_translate("MainWindow", "Read C", None))
        self.pushButton_54.setText(_translate("MainWindow", "Read D", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Monitors", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "PID Settings", None))
        self.label_17.setText(_translate("MainWindow", "Winch A", None))
        self.label_29.setText(_translate("MainWindow", "Kp", None))
        self.label_34.setText(_translate("MainWindow", "Ki", None))
        self.label_35.setText(_translate("MainWindow", "Kd", None))
        self.lineEdit_17.setText(_translate("MainWindow", "0", None))
        self.lineEdit_18.setText(_translate("MainWindow", "0", None))
        self.lineEdit_19.setText(_translate("MainWindow", "0", None))
        self.pushButton_33.setText(_translate("MainWindow", "Read A", None))
        self.pushButton_47.setText(_translate("MainWindow", "Write A", None))
        self.label_18.setText(_translate("MainWindow", "Winch B", None))
        self.lineEdit_48.setText(_translate("MainWindow", "0", None))
        self.lineEdit_58.setText(_translate("MainWindow", "0", None))
        self.lineEdit_59.setText(_translate("MainWindow", "0", None))
        self.pushButton_37.setText(_translate("MainWindow", "Read B", None))
        self.pushButton_48.setText(_translate("MainWindow", "Write B", None))
        self.label_19.setText(_translate("MainWindow", "Winch C", None))
        self.lineEdit_66.setText(_translate("MainWindow", "0", None))
        self.lineEdit_67.setText(_translate("MainWindow", "0", None))
        self.lineEdit_68.setText(_translate("MainWindow", "0", None))
        self.pushButton_40.setText(_translate("MainWindow", "Read C", None))
        self.pushButton_49.setText(_translate("MainWindow", "Write C", None))
        self.label_20.setText(_translate("MainWindow", "Winch D", None))
        self.lineEdit_69.setText(_translate("MainWindow", "0", None))
        self.lineEdit_70.setText(_translate("MainWindow", "0", None))
        self.lineEdit_71.setText(_translate("MainWindow", "0", None))
        self.pushButton_43.setText(_translate("MainWindow", "Read D", None))
        self.pushButton_50.setText(_translate("MainWindow", "Write D", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Field Settings", None))
        self.label_52.setText(_translate("MainWindow", "Field Length (mm)", None))
        self.lineEdit_72.setText(_translate("MainWindow", "1000", None))
        self.label_53.setText(_translate("MainWindow", "Field Width (mm)", None))
        self.lineEdit_73.setText(_translate("MainWindow", "1000", None))
        self.pushButton_52.setText(_translate("MainWindow", "Write All", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Motion Settings", None))
        self.label_54.setText(_translate("MainWindow", "Max Velocity (mm/s)", None))
        self.lineEdit_74.setText(_translate("MainWindow", "50", None))
        self.label_55.setText(_translate("MainWindow", "Acceleration (mm/s^2)", None))
        self.lineEdit_75.setText(_translate("MainWindow", "50", None))
        self.pushButton_53.setText(_translate("MainWindow", "Write All", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Other Settings", None))
        self.label_8.setText(_translate("MainWindow", "Serial Port", None))
        self.lineEdit.setText(_translate("MainWindow", "COM8", None))
        self.pushButton_12.setText(_translate("MainWindow", "Connect", None))
        self.pushButton_13.setText(_translate("MainWindow", "Disconnect", None))
        self.pushButton_1.setText(_translate("MainWindow", "Emergency Stop", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

