class Holding_Registers:
        Winch_ID, \
        Soft_Reset, \
        Max_Velocity, \
        Max_Acceleration, \
        Target_Setpoint, \
        Target_Setpoint_Offset, \
        Kp, \
        Ki, \
        Kd, \
        PID_Setpoint, \
        Target_X, \
        Target_Y, \
        Target_Z, \
        Target_X_Offset, \
        Target_Y_Offset, \
        Target_Z_Offset, \
        Field_Length, \
        Field_Width, \
        Homing_switch, \
        Current_Encoder_Count, \
        Current_PWM, \
        Current_RPM, \
        Current_X, \
        Current_Y, \
        Current_Z, \
        Current_Length_Winch0, \
        Current_Length_Winch1, \
        Current_Length_Winch2, \
        Current_Length_Winch3, \
        Target_Length_Winch0, \
        Target_Length_Winch1, \
        Target_Length_Winch2, \
        Target_Length_Winch3, \
        Current_Force_Winch0, \
        Current_Force_Winch1, \
        Current_Force_Winch2, \
        Current_Force_Winch3, \
        ADC0, \
        ADC1, \
        ADC2, \
        ADC3, \
        Homing_Flag, \
        Kinematic_mode, \
        Sync, \
        Follow_Waypoints, \
        Current_Waypoints_Pointer, \
        Number_of_Waypoints, \
        Dwell_Time = range(48)

Map = Holding_Registers